apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "1niPa55word"
  DB_NAME: "tasks_db"
  DB_INSTANCE: "orca-lab01:asia-southeast2:tasks-db"
